name: ${project.name}
version: ${project.version}
authors: [The_TadeSK, Wertík (qwz)]
main: me.tade.mccron.Cron
commands:
  timer:
    description: Timer command
  mccron:
    description: Main plugin command